on:
  pull_request:
    branches: [ 'main' ]
  schedule:
    - cron: '0 * * * *'
jobs:
  compile:
    permissions:
      contents: write
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Compile
        run: |
          sudo apt update && sudo apt install -y dnsutils
          dig aaaa ghcr.io
          dig aaaa github.com
          dig aaaa api.github.com

